### ISSUE TITLE
Undefined behavior happens when I try to Chroot

### ISSUE THREAD

**Issue by ahmeducf** [codescalersinternships/salah-flist#1]
In the [Run](https://github.com/codescalersinternships/salah-flist-runner/blob/57fb33931f86a56a3eb4878d45686a0c9c436309/flist-run.go#L139) function, what I try to do is to first download the flist and then mount it at some temp location, then I try to execute the binary given at `entrypoint`.

At first, I tried to save flists metadata and containers data under one directory, I called it `flist`.
Just like what `docker` do, and saves all its data under `/var/lib/docker`, I save all my data at `/var/lib/flist`.

**Let me explain my work on an example:**

say we are give an flist of redis:

- The path of the downloaded flist metadata (archive file) will be at: `/var/lib/flist/store`
- The path of the container: `/var/lib/flist/containers/redis545465454`
- The path of the 0-fs backend: `/var/lib/flist/containers/redis545465454/backend`
- The path of the mountpoint: `/var/lib/flist/containers/redis545465454/mnt`

The tree rooted at `/var/lib/flist` will look like that:
![image](https://user-images.githubusercontent.com/53626822/188308000-16f64ee5-9e1c-4ead-9fd0-dd7fab1489bf.png)

*This is the code that tries to execute the binary at `entrypoint` after `Chroot`.*
```go
go func () error {
  if err := syscall.Chroot(mountpoint); err != nil {
    log.Println(err)
    return err
  }
  if err := syscall.Chdir("/"); err != nil {
    log.Println(err)
    return err
  }
  
  if err := syscall.Mount("proc", "proc", "proc", 0, ""); err != nil {
    log.Println(err)
    return err
  }
  if err := syscall.Mount("tmp", "tmp", "tmpfs", 0, ""); err != nil {
    log.Println(err)
    return err
  }
  
  cmd := exec.Command(entrypoint)
  cmd.Stdin = os.Stdin
  cmd.Stdout = os.Stdout
  cmd.Stderr = os.Stderr
  
  err := cmd.Run()
  if err != nil {
    log.Println(err)
    return err
  }
  return nil
  } ()
```
when I  run the process, the process **hangs** and I miss the control of it and beocome unable to send it **SIGINT** signals to kill it. The `0-fs` library also becomes unable to fetch files.

![image](https://user-images.githubusercontent.com/53626822/188306889-c77f2a59-5950-4b8e-8adc-b711b7625f57.png)

**Comment by muhamadazmy** [comment]
- You need to mount `proc` and `tmp` before you actually do a `chroot`, not after
- Why are u doing this in a `go routine` ?  you can't even handle the error this way because it's just dropped. and u just print the errors. 
- The right way to do this is to:
  - you mount the filesystem
  - you mount proc, tmp, etc..
  - (errors in previous steps should terminate the app)
  - before you proceed with the chroot you need to make a call to `runtime.LockOSThread()`. this is important because Go can run multiple threads to run the application (how the runtime handles the go routines). you need to make sure all the next calls run on the same thread. You can do chroot (so the current thread will do chroot) but then when u do `exec` it will run on another thread which hasn't chrooted. So this call will make sure all the next calls run on the same thread.
  - you then do a `chroot`
  - you exec your app (redis-server in this case)
  - when exec is done, you can unlock the os thread again
  - exit. (because you will exit anyway the unlocking is not needed but it's a good practice plus will make your code re-usable.

**Comment by ahmeducf** [comment]
I made all required changes that you commented, but the same problem still happens.
[run](https://github.com/codescalersinternships/salah-flist/blob/4cd929e544ef3bcc7f392d62d67b8735c5bbccc1/daemon/run.go#L139) function

**Comment by ahmeducf** [comment]
The problem was solved by providing more isolation for the container.
- configure Chroot inside the executed process, not in the parent.
- containerize the command by creating some namespaces

_This code snippet solved the problem:_
```go
cmd := exec.Command(flist.Entrypoint, flist.Arg...)
cmd.SysProcAttr = &syscall.SysProcAttr{
	Chroot: flist.Mountpoint,
	Cloneflags: syscall.CLONE_NEWUTS | syscall.CLONE_NEWNET | syscall.CLONE_NEWNS |
			syscall.CLONE_NEWUSER | syscall.CLONE_NEWPID,
	Unshareflags: syscall.CLONE_NEWNS,
	UidMappings: []syscall.SysProcIDMap{{
		ContainerID: 0,
		HostID: syscall.Getuid(),
		Size: 1,
	}},
	GidMappings: []syscall.SysProcIDMap{{
		ContainerID: 0,
		HostID: syscall.Getgid(),
		Size: 1,
	}},
	Credential: &syscall.Credential{
		Uid: uint32(syscall.Getuid()),
		Gid: uint32(syscall.Getuid()),
	},
	Pdeathsig: syscall.SIGKILL,
}
cmd.Stdin  = os.Stdin
cmd.Stdout = os.Stdout
cmd.Stderr = os.Stderr
```
